name: golf_detection_app
description: Application Flutter pour détecter les balles de golf et drapeaux avec calcul de distances
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Camera et permissions
  camera: ^0.10.5+5
  permission_handler: ^11.0.1
  
  # TensorFlow Lite pour l'IA
  tflite_flutter: ^0.10.4
  tflite_flutter_helper: ^0.3.1
  
  # Traitement d'images
  image: ^4.1.3
  path_provider: ^2.1.1
  
  # UI et état
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  
  # Utilitaires
  path: ^1.8.3
  gallery_saver: ^2.3.2
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700